language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3  

before_script:
  - composer self-update
  - touch storage/testing.sqlite
  - composer update -n --prefer-dist
  - php artisan migrate --env=testing --database=sqlite_testing --force
  - php artisan config:clear
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run
