language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 7.2

before_script:
  - composer self-update
  - touch storage/testing.sqlite
  - touch storage/database.sqlite
  - composer install -n --prefer-dist
  - php artisan migrate --env=testing --database=sqlite_testing --force
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run
